puts "Creando Arquitectos..."

Arquitecto.create!([
  {
    cedula: "4200000006",
    valoracion_prom_proyecto: 4.5,
    descripcion: "Especialista en arquitectura residencial",
    especialidades: "Arquitectura Residencial, Diseño Sostenible",
    ubicacion: "Quito-Pichincha-Ecuador",
    verificado: true,
    vistas_perfil: 45,
    usuario_id: "965da078-b598-42de-8a66-ddd67458932e",
  },
  {
    cedula: "4200000007",
    valoracion_prom_proyecto: 4.7,
    descripcion: "Experto en diseños comerciales modernos",
    especialidades: "Arquitectura Comercial, Retail Design",
    ubicacion: "Guayaquil-Guayas-Ecuador",
    verificado: true,
    vistas_perfil: 52,
    usuario_id: "66dcc9f6-6023-44c4-805b-1de7c79acfe1",
  },
  {
    cedula: "4200000008",
    valoracion_prom_proyecto: 4.3,
    descripcion: "Especialista en paisajismo y espacios verdes",
    especialidades: "Paisajismo, Diseño Urbano",
    ubicacion: "Cuenca-Azuay-Ecuador",
    verificado: true,
    vistas_perfil: 38,
    usuario_id: "f7ea97ae-5c31-4df9-a6e5-be1154af68ca",
  },
  {
    cedula: "4200000009",
    valoracion_prom_proyecto: 4.6,
    descripcion: "Restaurador de patrimonio histórico",
    especialidades: "Restauración Patrimonial, Conservación",
    ubicacion: "Ambato-Tungurahua-Ecuador",
    verificado: false,
    vistas_perfil: 28,
    usuario_id: "ccb95121-42ae-4b5a-a15b-6bb6a1a2278b",
  },
  {
    cedula: "4200000010",
    valoracion_prom_proyecto: 4.8,
    descripcion: "Diseñador de arquitectura bioclimática",
    especialidades: "Arquitectura Bioclimática, Sostenibilidad",
    ubicacion: "Loja-Loja-Ecuador",
    verificado: true,
    vistas_perfil: 61,
    usuario_id: "5ec7bdf2-35f8-4401-b5d8-965fd0a5d8cf",
  },
  {
    cedula: "4200000011",
    valoracion_prom_proyecto: 4.4,
    descripcion: "Experto en remodelaciones y ampliaciones",
    especialidades: "Remodelación, Ampliación",
    ubicacion: "Ibarra-Imbabura-Ecuador",
    verificado: true,
    vistas_perfil: 42,
    usuario_id: "41ada8f5-7877-46d9-ab19-2f689c58a976",
  },
  {
    cedula: "4200000012",
    valoracion_prom_proyecto: 4.9,
    descripcion: "Diseñador integral con enfoque sustentable",
    especialidades: "Diseño Integral, Sostenibilidad",
    ubicacion: "Esmeraldas-Esmeraldas-Ecuador",
    verificado: true,
    vistas_perfil: 55,
    usuario_id: "d3f6cde3-ddf8-4ee9-a95d-eaab8fd9df71",
  },
  {
    cedula: "4200000013",
    valoracion_prom_proyecto: 4.2,
    descripcion: "Especialista en proyectos residenciales de lujo",
    especialidades: "Residencial Lujo, Diseño Premium",
    ubicacion: "Tungurahua-Tungurahua-Ecuador",
    verificado: false,
    vistas_perfil: 35,
    usuario_id: "5536d07f-4730-4b2b-bb5a-438c203f3b3e",
  },
  {
    cedula: "4200000014",
    valoracion_prom_proyecto: 4.7,
    descripcion: "Experto en diseño de espacios comerciales",
    especialidades: "Comercial, Office Design",
    ubicacion: "Pichincha-Pichincha-Ecuador",
    verificado: true,
    vistas_perfil: 48,
    usuario_id: "db4e2d15-73cf-4c56-8b7f-bb6599e2e4e8",
  },
  {
    cedula: "4200000015",
    valoracion_prom_proyecto: 4.5,
    descripcion: "Diseñador de infraestructura y espacios públicos",
    especialidades: "Urbanismo, Espacios Públicos",
    ubicacion: "Guayas-Guayas-Ecuador",
    verificado: true,
    vistas_perfil: 50,
    usuario_id: "176425a1-ae08-4b98-8f2b-84593a0f99ac",
  }
])

puts "Arquitectos creados."
